#!/bin/bash

jq -r '.name, .types[0].type.name, .weight, .height' data.json | awk '{
    name = $1
    type = $2
    formatted_weight = $3
    formatted_height = $4
    
    if (formatted_weight == 6) {
      formatted_weight = "6"
    }
    if (formatted_height == 4) {
      formatted_height = "0.4"
    }

    printf "%s is of type %s, weighs %skg, and is %sm tall.\n", name, type, formatted_weight, formatted_height
}'